datasource:
  driverName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/building_machinery?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: Flyer
  password: Ca59563
  initialSize: 10
  maxActive: 7
#spring:
#  flyway:
#    ignore-missing-migrations: true
#    locations: classpath:/migrations
#    baseline-on-migrate: true
#    baseline-description: Flyway Scripts
---
mailconfig:
  mailAddress: buildin.machinery@gmail.com
  mailPassword: zgwdvidgkzzsjzts
  host: smtp.gmail.com
  port: 587
  localServer: http://localhost:8080/auth/confirmation?auth-token=
---
token:
  sshSecret: ThetopSecretforthetopsecret
  expirationTime: 720000000
---


