datasource:
  driverName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/building_machinery?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: Flyer
  password: Ca59563
  initialSize: 10
  maxActive: 7
---
mailconfig:
  mailAddress: buildin.machinery@gmail.com
  mailPassword: zgwdvidgkzzsjzts
  host: smtp.gmail.com
  port: 587

